name: flutter_project
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  url_launcher: ^4.0.3
  http: ^0.12.0+4
  google_maps_flutter: ^0.5.21+15
  geolocator: ^5.2.0
  location_permissions: ^2.0.4+1
  permission_handler: ^4.2.0+hotfix.2
  location: ^2.3.5
  provider: ^4.0.2
  cupertino_icons: ^0.1.2
  package_info: ^0.4.0+3
  app_settings: 3.0.0+1
  devicelocale: ^0.2.1
  flutter_calendar_carousel: ^1.4.10
  timezone: ^0.5.4
  flutter_screenutil: ^1.0.2
  shared_preferences: ^0.5.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: any
  shared_preferences: any




flutter:

  uses-material-design: true
  assets:
    - assets/urb.jpeg
    - assets/logocolor.png
    - assets/icons/parking.png
    - assets/icons/parking_carga.png
    - assets/icons/parking_minus.png
    - assets/logoblancoazul.png
    - assets/logoblancoazul2.png




